# Generated by Django 3.1.2 on 2021-07-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('term', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
