# Generated by Django 3.1.2 on 2021-07-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoName', models.CharField(max_length=50)),
                ('first_term', models.IntegerField()),
                ('second_term', models.IntegerField()),
                ('first_term_name', models.CharField(max_length=50)),
                ('second_term_name', models.CharField(max_length=50)),
            ],
        ),
    ]
